name: Maven Build and Run Tests 

on:
  push:
    branches: 
      - main
      - test-framework
  pull_request:
    branches: 
      - main
      - test-framework

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    - name: Set up JDK 17
      uses: actions/setup-java@v4
      with:
        java-version: '17'
        distribution: 'temurin'
        cache: maven
    - name: Build with Maven
      env:
         VAADIN_OFFLINE_KEY: ${{ secrets.VAADIN_PRODMODE_CI_SERVER_KEY }}
      run: mvn -B clean package -Pproduction --file pom.xml -DskipTests

    #- name: Run unit tests only
    #  env:
    #     VAADIN_OFFLINE_KEY: ${{ secrets.VAADIN_PRODMODE_CI_SERVER_KEY }}
    #  run: mvn -B verify -Pproduction --file pom.xml

    - name: Run tests
      env:
         VAADIN_OFFLINE_KEY: ${{ secrets.VAADIN_PRODMODE_CI_SERVER_KEY }}
      run: mvn -B verify -Pproduction,it --file pom.xml -Dcom.vaadin.testbench.Parameters.chromeOptions="--headless --disable-gpu"
